# Generated by Django 5.0 on 2023-12-13 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendMission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_all_certificated', models.BooleanField(default=False, verbose_name='인증 여부')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('trend_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trends.trend', verbose_name='trend')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='팔로우 하는 사용자')),
            ],
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='팔로우 하는 사용자')),
                ('trend_mission_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trend_missions.trendmission', verbose_name='트렌드 미션 아이디')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=300, verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trend_missions.comment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('trend_mission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trend_missions.trendmission', verbose_name='트렌드 미션 아이디')),
            ],
        ),
        migrations.CreateModel(
            name='UserTrendItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='인증날짜')),
                ('image', models.ImageField(upload_to='media/image/userTrendItem/', verbose_name='트렌드 아이템 인증 사진')),
                ('is_certificated', models.BooleanField(default=False, verbose_name='인증 여부')),
                ('content', models.CharField(max_length=300, verbose_name='트렌드 아이템 인증 내용')),
                ('trend_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.trenditem', verbose_name='트렌드 아이템 아이디')),
                ('trend_mission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trend_missions.trendmission', verbose_name='트렌드 미션 아이디')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
    ]
