# Generated by Django 5.0 on 2023-12-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='트렌드 이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TrendItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='트렌드 아이템 제목')),
                ('content', models.CharField(max_length=300, verbose_name='트렌드 아이템 내용')),
                ('image', models.ImageField(upload_to='media/image/trendItem/', verbose_name='트렌드 아이템 사진')),
                ('trend_id', models.ManyToManyField(to='trends.trend', verbose_name='trend_id')),
            ],
        ),
    ]
