name: Django CI/CD

on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃 레포지토리
        uses: actions/checkout@v3

      - name: 파이썬 설정
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: 의존성 설치
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: 서버 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            set -e
            cd /home/ubuntu/HotCake-BE
            git pull origin deploy

            echo "DEBUG='${{ secrets.DEBUG }}'" >> .env
            echo "DATABASES_ENGINE=\"${{ secrets.DATABASES_ENGINE }}\"" >> .env
            echo "DATABASES_NAME=\"${{ secrets.DATABASES_NAME }}\"" >> .env
            echo "DATABASES_USER=\"${{ secrets.DATABASES_USER }}\"" >> .env
            echo "DATABASES_PASSWORD=\"${{ secrets.DATABASES_PASSWORD }}\"" >> .env
            echo "DATABASES_HOST=\"${{ secrets.DATABASES_HOST }}\"" >> .env
            echo "DATABASES_PORT=\"${{ secrets.DATABASES_PORT }}\"" >> .env
            echo "KAKAO_REST_API_KEY=\"${{ secrets.KAKAO_REST_API_KEY }}\"" >> .env
            echo "KAKAO_REDIRECT_URI=\"${{ secrets.KAKAO_REDIRECT_URI }}\"" >> .env
            echo "KAKAO_CLIENT_SECRET_KEY=\"${{ secrets.KAKAO_CLIENT_SECRET_KEY }}\"" >> .env
            echo "KAKAO_LOGOUT_REDIRECT_URI=\"${{ secrets.KAKAO_LOGOUT_REDIRECT_URI }}\"" >> .env
            
            source /home/ubuntu/venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart hotcake.service
